version: "3.7"

networks:
  docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: docker.php
    tty: true
    depends_on:
      - mysql
      - redis
    networks:
      - docker.network
    volumes:
      - .:/var/www

  nginx:
    build: ./docker/nginx
    container_name: docker.nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - php
    ports:
      - "433:433"
      - "80:80"
    networks:
      - docker.network
    volumes:
      - .:/var/www

  # apache:
  #   build: ./docker/apache
  #   restart: unless-stopped
  #   container_name: docker.apache
  #   tty: true
  #   depends_on:
  #     - php
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - docker.network
  #   volumes:
  #     - .:/var/www

  #  mariadb:
  #    image: mariadb
  #    restart: unless-stopped
  #    container_name: docker.mariadb
  #    tty: true
  #    ports:
  #      - '3306:3306'
  #    networks:
  #      - docker.network
  #    volumes:
  #      - './docker/mysql/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro'
  #      - './docker/mysql/dbdata:/var/lib/mysql'
  #    environment:
  #      MYSQL_DATABASE: ${MYSQL_DATABASE:-development}
  #      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
  #      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
  #      MYSQL_USER: ${MYSQL_USER:-mysql}

  mysql:
    image: mysql:5
    restart: unless-stopped
    container_name: docker.mysql
    tty: true
    ports:
      - "3306:3306"
    networks:
      - docker.network
    volumes:
      - "./docker/mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
      - "./docker/mysql/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-development}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
      MYSQL_USER: ${MYSQL_USER:-mysql}

  phpmyadmin:
    image: phpmyadmin
    container_name: docker.phpmyadmin
    tty: true
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - docker.network
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      PMA_PORT: 3306


  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    container_name: docker.redis
    tty: true
    ports:
      - "6379:6379"
    networks:
      - docker.network
    volumes:
      - ./docker/redis:/bitnami/redis/data
    environment:
      ALLOW_EMPTY_PASSWORD: ${REDIS_ALLOW_EMPTY_PASSWORD:-no}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
